### ISSUE TITLE
unresponsive logo image

### ISSUE THREAD

**Issue by HilmiZul** [binaroom/binaroom.github.io#4]
https://github.com/binaroom/binaroom.github.io/blob/dd039246cc0972d4c3dd7cce5475c30ae07dbbc9/index.html#L24
i think this image size unresponsive when open in mobile device.
can we fix this issue?

**Comment by binaroom** [comment]
fix now.
thanks.

**Comment by HilmiZul** [comment]
I just made a pull request to fix this issue

**Comment by binaroom** [comment]
okay, I'll review

**Comment by binaroom** [comment]
okay thanks
